### ISSUE TITLE
Setting up packagist webhook

### ISSUE THREAD

**Issue by lasselehtinen** [neoxia/laravel-csv-response#14]
Hi,

Could you setup/fix the packagist webhook for this package? The release 1.1.6 was done 7 days ago but it still does not appear in packagist. They automatically crawl these once per week, but it would be nice if the releases would be pushed automatically.

![image](https://user-images.githubusercontent.com/1290186/65696617-3b7e1600-e082-11e9-9a3d-f90b700c5e35.png)

**Comment by flaforgue** [comment]
Hi @lasselehtinen , thank you for the information. I don't have the right access on Packagist but I think @thomasruiz should and it will be fixed soon!

**Comment by flaforgue** [comment]
Hello @lasselehtinen , the repo was still using the deprecated "Github Services", it has now been automatically configured in Github Webhooks by Packagist.
