### ISSUE TITLE
Support to laravel 7

### ISSUE THREAD

**Issue by netoramalho** [neoxia/laravel-csv-response#16]
Hey guys, is there any plan to support Laravel 7?

I'm trying to install here without success?

Thank you

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v7.4.0
    - Conclusion: don't install laravel/framework v7.4.0
```

**Comment by josiahke** [comment]
hello, any update on this request?

**Comment by AntoninWelvart** [comment]
Hello @josiahke & @netoramalho , the release of the last version (v1.1.7) supports laravel 7.
