### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by honeypc** [neoxia/laravel-csv-response#6]
I got this errors. Anyone help me resolve it

- don't install illuminate/routing v5.5.39|don't install laravel/framework v5.6.21
    - don't install illuminate/routing v5.5.40|don't install laravel/framework v5.6.21
    - Installation request for laravel/framework (locked at v5.6.21, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.21].
    - Installation request for neoxia/laravel-csv-response ^1.1 -> satisfiable by neoxia/laravel-csv-response[v1.1.0, v1.1.1, v1.1.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by mathieutu** [comment]
It will be fixed in https://github.com/neoxia/laravel-csv-response/pull/7

**Comment by alexandre-butynski** [comment]
Hi @honeypc !

Sorry for the delay but I have just published a new release ([v1.1.3](https://github.com/neoxia/laravel-csv-response/releases/tag/v1.1.3)) compatible with Laravel 5.6. Let us know if it fixes your issue.
